language: python
dist: xenial
services:
  - xvfb
python:
  - 2.7
  - 3.6

addons:
  firefox: "66.0"

install:
  - pip install -r requirements.txt
  - pip install coverage codecov selenium
  - python setup.py develop

before_script:
  - firefox --version
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - coverage erase
  - coverage run -p -m pytest -v vixen/tests
  - coverage run -p -m pytest -v vixen/integration_tests
  - coverage combine

after_success:
  - coverage report
  - codecov
